name: Metrics
on:
  schedule: [{cron: "30 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_twemoji: yes
          config_gemoji: yes
          plugin_languages: yes
          plugin_languages_threshold: 2%
          plugin_languages_details: bytes-size, percentage
          plugin_followup: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14  
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stars: yes
          plugin_stars_limit: 4  
          plugin_stargazers: yes
          plugin_isocalendar: yes  
          plugin_isocalendar_duration: full-year  
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: all  
          plugin_people: yes
          plugin_people_types: followers, sponsors 
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_identicons: no
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 4
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_played_at: yes
